---
- name: Deploy static website to web server
  hosts: webservers
  become: yes
 
  tasks:
    - name: Copy HTML/CSS/JS files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0644'
      with_fileglob:
        - "*.html"
        - "*.css"
        - "*.js"
 
    - name: Copy images
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0644'
      with_fileglob:
        - "*.png"
        - "*.jpg"
        - "*.jpeg"
        - "*.gif"
 
    - name: Restart Apache
      ansible.builtin.service:
        name: apache2
        state: restarted
